export const NOTION = {
  NOTION_API_KEY: process.env.NEXT_PUBLIC_NOTION_API_KEY,
  DEFAULT_PAGE_DATABASE_ID: process.env.NEXT_PUBLIC_NOTION_PAGE_DATABASE_ID,
  POSTS_DATABASE_ID: process.env.NEXT_PUBLIC_NOTION_POSTS_DATABASE_ID,
  ABOUT_DATABASE_ID: process.env.NEXT_PUBLIC_NOTION_ABOUT_DATABASE_ID,
}
